import 'server-only';

// Distractor label pool for the "Nişan Tapmacası" (road sign riddle) game.
//
// Every string here is a SHORT official name of a real Azerbaijani traffic
// sign, extracted (deduplicated) from the table in public/nisanlar.pdf — the
// same document that feeds getSignPool(). These are the text the options
// display. Keeping them here as static data (rather than querying the DB)
// gives the round builder a rich distractor source with no DB dependency:
// the game's QUESTIONS come from the curated nisan_tapmacasi_questions rows
// (code + hand-written hint), their images from the live sign pool, and only
// the three wrong answers per question are drawn from this list.
//
// They are intentionally just NAMES — the official one-line description for
// the sign, exactly as it appears in the "Kod | Təsvir | Lövhə" table. The
// full pool descriptions (which would double as the answer) live in the sign
// pool and are deliberately NOT used here.

// Sorted alphabetically (az-locale-ish) for stable diffs. Do not hand-add
// labels — re-extract from the PDF table if the corpus grows.
export const NISAN_TAPMACASI_LABELS: readonly string[] = [
  'Alçaqdan uçan təyyarələr',
  'At-araba ilə hərəkət qadağandır',
  'Avtobusun və ya trolleybusun dayanacaq yeri',
  'Avtomagistral',
  'Avtomobillər üçün yol',
  'Avtomobillər üçün yolun qurtaracağı',
  'Avtomobillərin yuyulma məntəqəsi',
  'Avtomobillərə texniki xidmət',
  'Ayrılan körpü',
  'Ayın cüt günlərində durmaq qadağandır',
  'Ayın tək günlərində durmaq qadağandır',
  'Baş yol',
  'Baş yolun sonu',
  'Başqa işlək hissəyə yerdəyişmənin ilkin göstəricisi',
  'Birtərəfli hərəkət yoluna çıxış',
  'Birtərəfli yol',
  'Birtərəfli yolun qurtaracağı',
  'Birxətli dəmir yolu',
  'Bütün məhdudiyyətlər zonasının qurtaracağı',
  'Dairəvi hərəkət',
  'Dalan',
  'Dayanmadan keçmək qadağandır',
  'Daş uçqunu',
  'Digər təhlükələr',
  'Dincəlmə yeri',
  'Duracaq yeri',
  'Durmaq qadağandır',
  'Döngənin istiqaməti',
  'Düzünə və ya sağa hərəkət',
  'Düzünə və ya sola hərəkət',
  'Dəmir yol keçidinə yaxınlaşma',
  'Ehtiyat üçün ayrılmış duracaq yeri',
  'Enin məhdudlaşdırılması',
  'Eyni istiqamətli nəqliyyat axınlarını birləşdirir',
  'Eyni əhəmiyyətli yolların kəsişməsi',
  'Geriyə dönmə yeri',
  'Geriyə dönmə yerinin zonası',
  'Geriyə dönmək qadağandır',
  'Giriş qadağandır',
  'Gömrükxana',
  'Hündürlüyün məhdudlaşdırılması',
  'Hərəkət sxemi',
  'İkinci dərəcəli yolla kəsişmə',
  'İkitərəfli hərəkət',
  'İlk tibbi yardım məntəqəsi',
  'İnformasiya stendi',
  'İstiqamət göstəricisi',
  'İstiqamətin ilkin göstəricisi',
  'İstiqamətlərin ilkin göstəricisi',
  'İçməli su',
  'Killometr göstəricisi',
  'Küçənin istiqaməti',
  'Kənardankeçmə sxemi',
  'Maksimum sürətin məhdudlaşdırılması',
  'Mal-qara keçidi',
  'Maneəni sağdan keçmə',
  'Maneəni sağdan və ya soldan keçmə',
  'Maneəni soldan keçmə',
  'Marşrut nömrəsi və istiqaməti',
  'Marşrut nəqliyyat vasitələri üçün zolaq',
  'Marşrut nəqliyyat vasitələri üçün zolağı olan yol',
  'Mehmanxana və ya motel',
  'Minik avtomobillərinin hərəkəti',
  'Minik taksilərinin dayanacaq yeri',
  'Minimum ara məsafənin məhdudlaşdırılması',
  'Minimum sürətin məhdudlaşdırılması',
  'Motosikletlərin hərəkəti qadağandır',
  'Məsafələr göstəricisi',
  'Nahamar yol',
  'Nizamlanmayan piyada keçidini göstərir',
  'Oxa düşən ağırlığın məhdudlaşdırılması',
  'Piyada keçidi',
  'Piyada zolağı',
  'Piyadaların hərəkət istiqamətini göstərir',
  'Piyadaların hərəkəti qadağandır',
  'Polis hissəsi',
  'Qarşıdan hərəkətin üstünlüyü',
  'Qarşıdan hərəkətə nisbətən üstünlük',
  'Qarşılıqlı hərəkət',
  'Qarşılıqlı hərəkət yoluna çıxış',
  'Qarşılıqlı hərəkətin qurtaracağı',
  'Qoşqu ilə hərəkət qadağandır',
  'Sahilboyuna çıxış',
  'Sağa hərəkət',
  'Sağa və ya sola hərəkət',
  'Sola dönmək qadağandır',
  'Sola hərəkət',
  'Soldan ikinci dərəcəli yolun bitişməsi',
  'Stop-xətt',
  'Svetoforla nizamlama',
  'Sürüşkən yol',
  'Sərt eniş',
  'Sərt yoxuş',
  'Səs siqnalı vermək qadağandır',
  'Telefon',
  'Traktorların hərəkəti qadağandır',
  'Tramvay xətti ilə kəsişmə',
  'Tramvayın dayanacaq yeri',
  'Tualet',
  'Tunel',
  'Tövsiyə edilən sürət',
  'Təhlükə',
  'Təhlükəli döngə',
  'Təhlükəli döngələr',
  'Uzunluğun məhdudlaşdırılması',
  'Uşaqlar',
  'Velosiped zolağı ilə kəsişmə',
  'Velosipedlə hərəkət qadağandır',
  'Vəhşi heyvanlar',
  'Yanacaqdoldurma məntəqəsi',
  'Yaşayış məntəqəsinin başlanğıcı',
  'Yaşayış məntəqəsinin qurtaracağı',
  'Yeməkxana',
  'Yeraltı piyada keçidi',
  'Yerüstü piyada keçidi',
  'Yol işləri',
  'Yol polisinin daimi məntəqəsi',
  'Yol ver',
  'Yolun daralması',
  'Yük avtomobilləri üçün hərəkət istiqaməti',
  'Yük avtomobillərinin hərəkəti qadağandır',
  'Yük avtomobillərinin ötməsi qadağandır',
  'Zolaqlarda hərəkət istiqamətləri',
  'Zolağın başlanğıcı',
  'Zolağın qurtaracağı',
  'Çimərlik',
  'Çoxxətli dəmir yolu',
  'Ötmək qadağandır',
  'Ötməyin qadağan edildiyi zonanın qurtaracağı',
  'Şlaqbaumlu dəmir yol keçidi',
  'Şlaqbaumsuz dəmir yol keçidi',
  'Əks istiqamətli nəqliyyat axınlarını ayırır',
] as const;
